spring:
  datasource:
    url: ${SQLSERVER_URL}
    username: ${SQLSERVER_USER}
    password: ${SQLSERVER_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: uhta
        format_sql: true
    open-in-view: false
    show-sql: false
  flyway:
    schemas: uhta
    create-schemas: true
    enabled: true

server:
  port: 8080
logging:
  file:
    path: "./logs"
  level:
    com.vyatsu.lukoilweb.controllers: DEBUG

secrets:
  secret: NNErh2cZgc23m1VIg8Lzj0zWp3Gu6YMu