spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MSSQLServer;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        default_schema: uhta
        format_sql: true
    open-in-view: false
  flyway:
    schemas: uhta
    create-schemas: true
    enabled: true